__author__ = 'emrullah'


# football field
FOOTBALL_FIELD_MIN_X = 0.0
FOOTBALL_FIELD_MAX_X = 105.0
FOOTBALL_FIELD_MIN_Y = 0.0
FOOTBALL_FIELD_MAX_Y = 70.0

# goalpost
GOALPOST_MIN_X = 0.0
GOALPOST_MAX_X = 105.0
GOALPOST_MIN_Y = 30.0
GOALPOST_MAX_Y = 40.0
GOALPOST_LENGTH = 10.0

# arrow (direction and speed)
INITIAL_ARROW_SIZE = 2

# pass
GOAL_COEFFICIENT = 1000