__author__ = 'emrullah'


# football field
FOOTBALL_FIELD_MIN_X = 0.0
FOOTBALL_FIELD_MAX_X = 105.0
FOOTBALL_FIELD_MIN_Y = 0.0
FOOTBALL_FIELD_MAX_Y = 65.0

# goalpost
GOALPOST_MIN_X = 0.0
GOALPOST_MAX_X = 105.0
GOALPOST_MIN_Y = 28.25
GOALPOST_MAX_Y = 36.75
GOALPOST_LENGTH = 8.5

# arrow (direction and speed)
INITIAL_ARROW_SIZE = 2

# pass
GOAL_COEFFICIENT = 1000